from pathlib import Path

MODEL_PATH = Path("models")
DATA_PATH = Path("data")

DEFAULT_USER = "admin"
DEFAULT_SMART_FAQ = None
DEFAULT_KNOWLEDGE_BASES = []
USE_VANILLA_LLM = True

CHUNK_SIZE = 512
CHUNK_OVERLAP_PCT = 15
TEMPERATURE = 0.0
MAX_TOKENS = 2560
MAXIMAL_MARGINAL_RELEVANCE = True
DISTANCE_METRIC = "cos"
K_FETCH_K_RATIO = 5

ENABLE_ADVANCED_OPTIONS = False
STORE_DOCS_EXTRA = False
LOCAL_DEEPLAKE = False
LOCAL_EMBEDDINGS = False

VERBOSE = True
